spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

